### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Vannico233** [WangQvQ/Ultralytics-PySide6#10]
Error: load_inference_source() got an unexpected keyword argument 'imgsz'
Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2023.3.3\PycharmProjects\Ultralytics-PySide6-main\main.py", line 116, in run
    self.setup_source(
  File "D:\PyCharm Community Edition 2023.3.3\PycharmProjects\Ultralytics-PySide6-main\main.py", line 499, in setup_source
    self.dataset = load_inference_source(
TypeError: load_inference_source() got an unexpected keyword argument 'imgsz'

**Comment by LuoItsuka** [comment]
注释掉“imgsz=self.imgsz,”就可以运行了

**Comment by LTHMine** [comment]
请问解决了吗，遇到了一样的问题
